services:
  db:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: ecopass
      POSTGRES_DB: ecopass
      POSTGRES_USER: ecopass
    ports:
      - "5432:5432"

  maildev:
    image: maildev/maildev
    ports:
      - '1080:1080'
      - '1025:1025'