services:
  db:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: ecopass
      POSTGRES_DB: ecopass
      POSTGRES_USER: ecopass
    ports:
      - "5432:5432"
  db_test:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: ecopass_test
      POSTGRES_DB: ecopass_test
      POSTGRES_USER: ecopass_test
    ports:
      - "5433:5432"
  maildev:
    image: maildev/maildev
    ports:
      - '1080:1080'
      - '1025:1025'