allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  '@scarf/scarf': true
  '@tree-sitter-grammars/tree-sitter-yaml': true
  bcrypt: true
  core-js-pure: true
  esbuild: true
  prisma: true
  sharp: true
  tree-sitter: true
  tree-sitter-json: true
  unrs-resolver: true
