import { OrganizationType } from "@prisma/enums"

export const nafs: Record<string, string> = {
  "01.11Z": "Culture de céréales (à l’exception du riz), de légumineuses et de graines oléagineuses",
  "01.12Z": "Culture de la canne à sucre",
  "01.13Z": "Culture du riz",
  "01.14Z": "Culture de légumes, de melons, de racines et de tubercules",
  "01.15Z": "Culture de la banane",
  "01.16Z": "Culture de la fibre",
  "01.19Z": "Autres cultures non permanentes",
  "01.21Z": "Culture de la vigne",
  "01.22Z": "Culture de fruits à pépins et à noyau",
  "01.23Z": "Culture de fruits tropicaux et subtropicaux",
  "01.24Z": "Culture d’agrumes",
  "01.25Z": "Culture de fruits oléagineux",
  "01.26Z": "Culture de plantes à boissons",
  "01.27Z": "Culture de plantes à épices, aromatiques, médicinales, toxiques et aromatiques",
  "01.28Z": "Culture de plantes textile",
  "01.29Z": "Autres cultures permanentes",
  "01.30Z": "Reproduction de plantes",
  "01.41Z": "Élevage de vaches laitières",
  "01.42Z": "Élevage d’autres bovins et de buffles",
  "01.43Z": "Élevage de chevaux et d’autres équidés",
  "01.44Z": "Élevage de camélidés et de la faune sauvage",
  "01.45Z": "Élevage d’ovins et de caprins",
  "01.46Z": "Élevage de porcins",
  "01.47Z": "Élevage de volailles",
  "01.49Z": "Autres élevages",
  "01.50Z": "Activités de soutien aux cultures et à l’élevage",
  "01.61Z": "Activités de services annexes à l’agriculture",
  "01.62Z": "Activités de soutien à l’agriculture",
  "01.63Z": "Traitement primaire des produits agricoles",
  "01.64Z": "Traitement des semences",
  "01.70Z": "Chasse, piégeage, services annexes",
  "01.91Z": "Activités de soutien à la production animale",
  "01.92Z": "Culture de champignons et truffes",
  "01.99Z": "Autres activités de soutien à l’agriculture",
  "02.10Z": "Sylviculture et autre activité forestière",
  "02.20Z": "Exploitation forestière",
  "02.30Z": "Récolte de produits forestiers non ligneux",
  "02.40Z": "Services de soutien à la sylviculture",
  "03.11Z": "Pêche en mer",
  "03.12Z": "Pêche en eau douce",
  "03.21Z": "Aquaculture en mer",
  "03.22Z": "Aquaculture en eau douce",
  "05.10Z": "Extraction de houille",
  "05.20Z": "Extraction de lignite",
  "06.10Z": "Extraction de pétrole brut",
  "06.20Z": "Extraction de gaz naturel",
  "07.10Z": "Extraction de minerais de fer",
  "07.21Z": "Extraction de minerais d’uranium et de thorium",
  "07.29Z": "Autres activités de soutien pour l’extraction de minerais métalliques",
  "08.11Z": "Carrières de pierres ornementales et de construction",
  "08.12Z": "Carrières de roches massives",
  "08.91Z": "Extraction de minerais de métaux précieux",
  "08.92Z": "Extraction de minerais de métaux non ferreux",
  "08.93Z": "Extraction de minerais d’autres substances",
  "08.99Z": "Extr. d’autres minerais non métalliques n.c.a.",
  "09.10Z": "Activités de soutien pour l’extraction de pétrole et de gaz naturel",
  "09.90Z": "Activités de soutien pour autres activités extractives",
  "10.11Z": "Transformation et conservation de la viande de boucherie",
  "10.12Z": "Transformation et conservation de la viande de volaille",
  "10.13A": "Préparation industrielle de produits à base de viande",
  "10.13B": "Charcuterie",
  "10.20Z": "Transformation et conservation de poisson, de crustacés et de mollusques",
  "10.31Z": "Transformation et conservation de pommes de terre",
  "10.32Z": "Préparation de jus de fruits et de légumes",
  "10.39Z": "Autres transformations et conservations de légumes",
  "10.41A": "Fabrication d’huiles et graisses",
  "10.41B": "Fabrication d’huiles essentielles",
  "10.42Z": "Fabrication de margarine et graisses comestibles",
  "10.51A": "Fabrication de produits laitiers frais",
  "10.51B": "Fabrication de glaces et sorbets",
  "10.52Z": "Fabrication de fromages",
  "10.71A": "Fabrication de pains et pâtisseries frais",
  "10.71B": "Biscuiterie",
  "10.72A": "Fabrication de biscuits salés et de produits de grignotage",
  "10.72B": "Fabrication de biscuits sucrés",
  "10.73Z": "Fabrication de pâtes alimentaires, couscous et produits farin. similaires",
  "10.81A": "Industrialisation de fruits",
  "10.81B": "Préparation de café, thé et épices",
  "10.82Z": "Fabrication de cacao et de chocolat",
  "10.83Z": "Fabrication de confiserie",
  "10.84Z": "Fabrication de produits alimentaires homogènes",
  "10.85Z": "Fabrication d’aliments nutritifs et de diététiques",
  "10.86Z": "Fabrication de préparations pour les animaux de ferme",
  "10.91Z": "Fabrication d’aliments pour animaux de compagnie",
  "10.92Z": "Fabrication d’aliments pour animaux d’élevage",
  "11.01Z": "Production de boissons alcooliques distillées",
  "11.02Z": "Production de vins",
  "11.03Z": "Production de cidre et de vins de fruits",
  "11.04Z": "Production de boissons rafraîchissantes non alcoolisées",
  "11.05Z": "Industrie des eaux de table",
  "12.00Z": "Culture de tabac",
  "13.10Z": "Préparation de fibres textiles",
  "13.20Z": "Tissage",
  "13.30Z": "Ennoblissement textile",
  "13.91Z": "Fabrication d’articles textiles, sauf habillement",
  "13.92Z": "Fabrication d’articles en bonneterie",
  "13.93Z": "Fabrication d’articles en dentelle, broderie",
  "13.94Z": "Fabrication de cordage, de ficelle, de filets, de tresses",
  "13.95Z": "Fabrication de tapis et moquettes",
  "13.96Z": "Fabrication de non-tissés, sauf habillement",
  "13.99Z": "Autres industrie textile n.c.a.",
  "14.11Z": "Fabrication de vêtements en cuir",
  "14.12Z": "Fabrication d’articles chaussants en cuir",
  "14.13Z": "Fabrication de vêtements de travail",
  "14.19Z": "Fabrication d’autres vêtements et accessoires",
  "14.20Z": "Fabrication d’articles de bonneterie",
  "14.31Z": "Fabrication d’articles chaussants à tiges, cuir",
  "14.39Z": "Fabrication d’autres articles chaussants",
  "14.91Z": "Fabrication de fourrures et articles en fourrure",
  "14.92Z": "Fabrication d’articles de harnachement et d’articles funéraires",
  "14.99Z": "Fabrication d’articles divers en cuir; sellerie, maroquinerie",
  "15.11Z": "Travaux de production d'électricité",
  "15.12Z": "Production de vapeur; distribution d’eau chaude",
  "15.20Z": "Production de combustibles gazeux",
  "15.30Z": "Production d’eau chaude sanitaire",
  "16.10A": "Sciage et rabotage du bois, hors imprégnation",
  "16.10B": "Holz (transformation du bois) divers",
  "16.21Z": "Fabrication de placage et de panneaux de bois",
  "16.22Z": "Fabrication de parquets assemblés",
  "16.23Z": "Fabrication de charpente et d’ossature du bois",
  "16.24Z": "Fabrication d’éléments en bois pour la construction",
  "16.29Z": "Fabrication d’autres ouvrages en bois",
  "16.30Z": "Fabrication d’éléments en bois, liège, vannerie et sparterie",
  "16.91Z": "Fabrication d’articles en liège",
  "16.92Z": "Fabrication d’objets divers en bois",
  "16.99Z": "Fabrication d’articles en bois, liège, vannerie et sparterie n.c.a.",
  "17.11A": "Fabrication de pâte à papier",
  "17.11B": "Fabrication de papier et carton ondulé",
  "17.12Z": "Fabrication de papier et carton",
  "17.20Z": "Fabrication d’articles en papier ou en carton",
  "18.11Z": "Reproduction d’enregistrements",
  "18.12Z": "Imprimerie de journaux",
  "18.13A": "Imprimerie (hors journaux)",
  "18.13B": "Reproduction d’enregistrements",
  "18.14Z": "Reliure et activités connexes",
  "18.20Z": "Services d’impartition (édition de dictionnaires, annuaires, etc.)",
  "18.31Z": "Cokéfaction",
  "18.32Z": "Raffinage de pétrole",
  "19.20Z": "Traitement de matières plastiques",
  "20.11Z": "Fabrication de gaz industriels",
  "20.12Z": "Fabrication de colorants, pigments et produits chimiques inorganiques de base",
  "20.13Z": "Fabrication de produits azotés et d’engrais",
  "20.14Z": "Fabrication de matières plastiques de base",
  "20.15Z": "Fabrication de produits intermédiaires en chimie",
  "20.16Z": "Fabrication de biocarburants",
  "20.17Z": "Fabrication d’autres produits chimiques organiques de base",
  "20.20Z": "Fabrication de pesticides et autres produits agrochimiques",
  "20.30Z": "Fabrication de peintures, vernis, encres et mastics",
  "20.41Z": "Fabrication de savons, détergents et produits d’entretien",
  "20.42Z": "Fabrication de parfums et produits pour la toilette",
  "20.43Z": "Fabrication de produits d’entretien pour la maison",
  "20.51Z": "Fabrication de explosifs",
  "20.52Z": "Fabrication de colles",
  "20.53Z": "Fabrication de produits azotés",
  "20.59Z": "Fabrication d’autres produits chimiques n.c.a.",
  "20.60Z": "Fabrication de fibres synthétiques ou artificielles",
  "21.10Z": "Fabrication de produits pharmaceutiques de base",
  "21.20Z": "Fabrication de préparations pharmaceutiques",
  "22.11Z": "Fabrication et rechapage de pneumatiques",
  "22.19Z": "Fabrication d’autres articles en caoutchouc",
  "22.21Z": "Fabrication de plaques, feuilles, tubes et profils en matières plastiques",
  "22.22Z": "Fabrication d’emballages en matières plastiques",
  "22.23Z": "Fabrication d’articles techniques en matières plastiques",
  "22.29Z": "Fabrication d’autres produits en matières plastiques",
  "23.11Z": "Production de verre plat",
  "23.12Z": "Façonnage et transformation du verre plat",
  "23.19Z": "Autres fabrication de verre et produits dérivés",
  "23.20Z": "Fabrication de fibres de verre",
  "23.31Z": "Fabrication d’éléments en béton préfabriqué",
  "23.32Z": "Fabrication de produits de ciment",
  "23.41Z": "Fabrication de carreaux, briques, tuiles et produits en terre cuite",
  "23.42Z": "Fabrication d’articles en poterie, porcelaine et matériaux de construction en céramique",
  "23.43Z": "Fabrication de ciment, chaux et plâtre",
  "23.51Z": "Fabrication de béton prêt à l’emploi",
  "23.52Z": "Fabrication de mortiers et bétons secs",
  "23.61Z": "Fabrication de chaux et plâtre",
  "23.62Z": "Fabrication de produits d’agrégats, de granulats, sable et gravier",
  "23.63Z": "Fabrication de produits minéraux non métalliques n.c.a.",
  "23.70Z": "Taille, façonnage, traitement et finissage de pierres",
  "23.99Z": "Fabrication d’autres produits minéraux non métalliques n.c.a.",
  "24.10Z": "Sidérurgie",
  "24.20Z": "Production de tubes, de profilés creux et de construction",
  "24.31Z": "Métallerie",
  "24.32Z": "Travaux de serrurerie métall. et de structures métalliques",
  "24.33Z": "Les activités de forge, d’emboutissage, de matriçage",
  "24.34Z": "Tréfilage et laminage",
  "24.51A": "Fonderie, métaux ferreux",
  "24.51B": "Fonderie, métaux non ferreux",
  "24.52Z": "Fonderie de matériaux non ferreux",
  "25.10Z": "Fabrication de structures métalliques et parties de structures",
  "25.20Z": "Fabrication de générateurs de vapeur, sauf pour le chauffage central",
  "25.30Z": "Fabrication de radiateurs et chaudières",
  "25.40Z": "Fabrication d’armes",
  "25.50Z": "Forge, estampage, métallurgie des poudres",
  "25.61Z": "Traitement et revêtement des métaux",
  "25.62Z": "Découpage, emboutissage, matriçage",
  "25.71Z": "Fabrication de coutellerie",
  "25.72Z": "Fabrication d’outillage",
  "25.73Z": "Fabrication de serrures et ferrures",
  "25.91Z": "Fabrication d’ouvrages en métaux, n.c.a.",
  "25.92Z": "Fabrication de réservoirs, citernes et containers métalliques",
  "25.93Z": "Fabrication de radiateurs et de chaudières",
  "26.11Z": "Fabrication de composants électroniques",
  "26.12Z": "Fabrication de cartes électroniques assemblées",
  "26.20Z": "Fabrication d’ordinateurs et d’équipements périphériques",
  "26.30Z": "Fabrication d’équipements de communication",
  "26.40Z": "Fabrication d’équipements d’instrumentation, de mesure et de navigation",
  "26.51Z": "Fabric. d’éléments optiques et optroniques",
  "26.60Z": "Fabrication d’équipements électrique",
  "26.70Z": "Fabrication de moteurs, générateurs et transformateurs électriques",
  "26.80Z": "Fabrication de machines pour l’agriculture et la sylviculture",
  "26.90Z": "Fabrication de pièces détachées pour machines",
  "27.10Z": "Fabrication de moteurs et turbines, sauf pour aéronautique",
  "27.20Z": "Fabrication d’équipements de transmission",
  "27.30Z": "Fabrication d’(autres) machines d’usage général",
  "27.40Z": "Fabrication de machines agricoles et forestières",
  "27.51Z": "Fabrication de machines pour l’extraction ou la construction",
  "27.90Z": "Fabrication d’autres machines spécialisées",
  "28.11Z": "Machines pour l’agriculture et la sylviculture",
  "28.12Z": "Machines pour l’extraction ou la construction",
  "28.13Z": "Machines pour l’industrie alimentaire",
  "28.14Z": "Machines pour le textile, le cuir et l’habillement",
  "28.15Z": "Machines pour le papier et le carton",
  "28.21Z": "Machines pour la fabrication de produits en caoutchouc ou en plastique",
  "28.29Z": "Autres machines pour usage général",
  "28.30Z": "Machines pour le moulage, la fonderie et le travail des métaux",
  "28.41Z": "Machines pour le travail du bois",
  "28.42Z": "Machines pour la fabrication de verre, de papier, etc.",
  "28.99Z": "Autres machines d’usage général n.c.a.",
  "29.10Z": "Construction de moteurs et turbines, sauf pour aéronautique",
  "29.20Z": "Fabrication d’équipements de transmission",
  "29.30Z": "Fabrication d’équipements pour moteurs",
  "29.31Z": "Fabric. d’engins mécaniques",
  "29.32Z": "Fabric. d’engins motorisés pour l’agriculture",
  "29.33Z": "Fabric. d’engins motorisés pour la construction",
  "29.35Z": "Fabric. d’engins motorisés pour la logistique",
  "29.90Z": "Fabric. de pièces",
  "30.11Z": "Construction navale",
  "30.12Z": "Construction de bateaux de plaisance",
  "30.20Z": "Construction de locomotives et d’équipements ferroviaires",
  "30.30Z": "Construction aéronautique",
  "30.91Z": "Construction de motocycles",
  "30.92Z": "Construction d’articles de sport (mécaniques)",
  "30.99Z": "Construction d’autres véhicules",
  "31.01Z": "Construction de meubles de bureau",
  "31.02Z": "Fabrication de meubles de cuisine",
  "31.03Z": "Fabrication de meubles de chambre à coucher",
  "31.04Z": "Fabrication de matelas",
  "31.05Z": "Fabrication d’autres meubles",
  "32.11Z": "Fabrication d’articles de joaillerie, bijouterie",
  "32.12Z": "Fabrication d’articles d’horlogerie",
  "32.13Z": "Fabrication d’articles de bijouterie fantaisie",
  "32.20Z": "Fabrication d’instruments de musique",
  "32.30Z": "Fabrication d’articles de sports",
  "32.40Z": "Fabrication de jeux et jouets",
  "32.50Z": "Fabrication d’articles de loisirs",
  "33.11Z": "Réparation d’ouvrages en métal",
  "33.12Z": "Réparation de machines",
  "33.13Z": "Réparation d’équipements électroniques",
  "33.14Z": "Réparation d’équipements électriques",
  "33.15Z": "Réparation de bateaux",
  "33.16Z": "Réparation d’aéronefs",
  "33.17Z": "Réparation d’appareils de navigation et de contrôle",
  "33.19Z": "Réparation d’autres équipements",
  "33.20Z": "Installation de machines et d’équipements industriels",
  "35.11Z": "Production d’électricité",
  "35.12Z": "Transport par conduites (gaz, eau, etc.)",
  "35.13Z": "Chauffage et refroidissement urbain",
  "35.30Z": "Capture, traitement et distribution d’eau",
  "35.31Z": "Assainissement",
  "35.32Z": "Gestion des déchets",
  "35.33Z": "Dépollution et autres services de gestion des déchets",
  "35.40Z": "Collecte des eaux usées",
  "36.00Z": "Captage, traitement et distribution d’eau",
  "37.00Z": "Collecte des eaux usées",
  "38.11Z": "Collecte des déchets non dangereux",
  "38.12Z": "Collecte des déchets dangereux",
  "38.21Z": "Traitement des déchets non dangereux",
  "38.22Z": "Traitement des déchets dangereux",
  "38.31Z": "Démantèlement d’éléments matériels",
  "38.32Z": "Valorisation ou élimination",
  "38.91Z": "Dépollution et autres services de gestion des déchets",
  "38.99Z": "Autres services de gestion des déchets",
  "39.00Z": "Dépollution et autres services de gestion des déchets",
  "41.10A": "Promotion immobilière de logements",
  "41.10B": "Promotion immobilière d’autres bâtiments",
  "41.20A": "Construction de maisons individuelles",
  "41.20B": "Construction d’autres bâtiments",
  "42.11Z": "Construction de routes et autoroutes",
  "42.12Z": "Construction de voies ferrées de transport",
  "42.13Z": "Construction de réseaux pour fluides",
  "42.21Z": "Construction de canalisations",
  "42.22Z": "Construction de lignes électriques",
  "42.91Z": "Construction d’ouvrages d’art",
  "42.99Z": "Construction d’autres ouvrages de génie civil",
  "43.11Z": "Travaux de démolition",
  "43.12Z": "Préparation de sites",
  "43.13Z": "Forages",
  "43.21Z": "Travaux de couverture",
  "43.22Z": "Travaux de charpente",
  "43.29Z": "Travaux de charpente métallique",
  "43.31A": "Travaux d’étanchéité",
  "43.31B": "Travaux d’étanchéité sur toitures-terrasses",
  "43.32A": "Travaux de portes et fenêtres",
  "43.32B": "Travaux de vitrerie",
  "43.33Z": "Travaux de menuiserie bois et PVC",
  "43.34Z": "Travaux de menuiserie métallique",
  "43.39Z": "Autres travaux de menuiserie",
  "43.91Z": "Travaux de plâtrerie",
  "43.99Z": "Autres travaux spécialisés",
  "44.10Z": "Commerce de voitures et de véhicules automobiles légers",
  "44.20A": "Commerce de gros de carburants et lubrifiants",
  "44.20B": "Commerce de détail de carburants en magasin spécialisé",
  "45.11Z": "Commerce d’automobiles et de véhicules automobiles légers",
  "45.19Z": "Entretien et réparation de véhicules automobiles légers",
  "45.20Z": "Maintenance et réparation de véhicules automobiles",
  "45.30Z": "Commerce et réparation de motocycles",
  "45.40Z": "Commerce d’équipements automobiles",
  "46.11Z":
    "Commerce de gros (commerce interentreprises) de céréales, tabac non transformé, semences et aliments pour le bétail",
  "46.12Z": "Commerce de gros de fleurs et plantes",
  "46.13Z": "Commerce de gros d’animaux vivants",
  "46.14Z": "Commerce de gros de denrées alimentaires",
  "46.15Z": "Commerce de gros de boissons",
  "46.16Z": "Commerce de gros de produits à base de tabac",
  "46.17Z": "Commerce de gros d’animaux de compagnie et d’animaux de ferme",
  "46.18Z": "Commerce de gros de produits pharmaceutiques",
  "46.19Z": "Commerce de gros de biens domestiques",
  "46.21Z": "Commerce de gros de céréales, tabac non transformé, semences et aliments pour le bétail",
  "46.22Z": "Commerce de gros de fruits et légumes",
  "46.23Z": "Commerce de gros de viandes et de produits à base de viande",
  "46.24Z": "Commerce de gros de poissons, crustacés et mollusques",
  "46.25Z": "Commerce de gros de produits laitiers, œufs, huiles et matières grasses comestibles",
  "46.26Z": "Commerce de gros de sucre, chocolat et produits de confiserie",
  "46.27Z": "Commerce de gros de café, thé, cacao et épices",
  "46.28Z": "Commerce de gros de produits surgelés",
  "46.29Z": "Commerce de gros de produits alimentaires divers",
  "46.30Z": "Commerce de gros de boissons et de produits à base de tabac",
  "46.31Z": "Courtiers en produits alimentaires",
  "46.32Z": "Commerce de gros de matériel agricole",
  "46.33Z": "Commerce de gros d’animaux vivants",
  "46.34Z": "Commerce de gros de fournitures et équipements industriels",
  "46.35Z": "Commerce de gros de déchets et ferrailles",
  "46.36Z": "Commerce de gros de mobilier de bureau",
  "46.37Z": "Commerce de gros d’ordinateurs, équipements périphériques et logiciels",
  "46.38Z": "Commerce de gros d’équipements électroniques & électro-ménagers",
  "46.39Z": "Commerce de gros d’autres machines et équipements",
  "46.40Z": "Commerce de gros de quincaillerie et fournitures",
  "46.41A": "Commerce de gros de composants électroniques et équipements informatiques",
  "46.41B": "Commerce de gros de quincaillerie et fournitures industrielles",
  "46.41Z": "Commerce de gros (commerce interentreprises) de textiles",
  "46.42Z": "Commerce de gros d’appareils électroménagers",
  "46.43Z": "Commerce de gros d’articles pharmaceutiques",
  "46.44Z": "Commerce de gros de parfumerie et produits de beauté",
  "46.45Z": "Commerce de gros alimentaire spécialisé",
  "46.46Z": "Commerce de gros d’articles médicaux et orthopédiques",
  "46.47Z": "Commerce de gros d’articles d’horlogerie et de bijouterie",
  "46.48Z": "Commerce de gros d’autres intermédiaires",
  "46.49Z": "Commerce de gros divers",
  "46.51Z": "Commerce interentreprises de combustibles, métaux, minerais",
  "46.52Z": "Commerce interentreprises de produits chimiques",
  "46.61Z": "Commerce de gros de matériel agricole",
  "46.62Z": "Commerce de gros d’ordinateurs, équipements informatiques & logiciels",
  "46.69Z": "Commerce de gros spécialisé divers",
  "46.71Z": "Agents de commerce de produits divers",
  "46.72Z": "Agents de commerce de produits agricoles, animaux vivants, matières premières",
  "46.90Z": "Commerce interentreprises non spécialisé",
  "47.11A": "Commerce de détail de produits surgelés",
  "47.11B": "Commerce de détail alimentaire sur éventaires et marchés",
  "47.19Z": "Autres commerces de détail alimentaire en magasin spécialisé",
  "47.21Z": "Commerce de détail de fruits et légumes en magasin spécialisé",
  "47.22Z": "Commerce de détail de viandes et produits à base de viande",
  "47.29Z": "Autres commerces de détail alimentaire en magasin",
  "47.30Z": "Commerce de détail de carburants en magasin spécialisé",
  "47.41Z": "Commerce de détail de quincaillerie, peintures et verres",
  "47.42Z": "Commerce de détail de matériaux de construction, quincaillerie et matériel de chauffage",
  "47.43Z": "Commerce de détail d’appareils électroménagers",
  "47.44Z": "Commerce de détail d’appareils audio-vidéo",
  "47.45Z": "Commerce de détail de jeux et jouets",
  "47.46Z": "Commerce de détail d’articles de sport",
  "47.49Z": "Autres commerces de détail d’équipements du foyer n.c.a.",
  "47.51Z": "Commerce de détail de textiles",
  "47.52Z": "Commerce de détail de la mercerie, de la lingerie et des articles textiles pour la maison",
  "47.53Z": "Commerce de détail de chaussures et d’articles en cuir",
  "47.54Z": "Commerce de détail d’articles de sport et de loisirs",
  "47.61Z": "Commerce de détail de livres en magasin",
  "47.62A": "Commerce de détail de journaux et papeterie en magasin spécialisé",
  "47.62B": "Commerce de détail de fournitures de bureau",
  "47.63Z": "Commerce de détail de musique et vidéo",
  "47.64Z": "Commerce de détail d’articles d’horlogerie et de bijouterie",
  "47.65Z": "Commerce de détail de meubles",
  "47.71Z": "Commerce de détail de tapis et revêtements de sols",
  "47.72Z": "Commerce de détail d’appareils audio-vidéo",
  "47.73Z": "Commerce de détail d’appareils électroménagers",
  "47.74Z": "Commerce de détail de matériels de télécommunication",
  "47.75Z": "Commerce de détail d’ordinateurs, d’équipements périphériques et de logiciels",
  "47.76Z": "Commerce de détail d’articles de décoration",
  "47.77Z": "Commerce de détail de jeux et jouets",
  "47.78Z": "Commerce de détail de produits optiques",
  "47.79Z": "Commerce de détail d’autres biens domestiques",
  "47.81Z": "Commerce de détail dans les commerces de vêtements",
  "47.82Z": "Commerce de détail de chaussures",
  "47.83Z": "Commerce de détail d’articles de sport",
  "47.84Z": "Commerce de détail d’articles culturels",
  "47.85Z": "Commerce de détail alimentaire sur internet",
  "47.89Z": "Autre commerce de détail spécialisé",
  "47.91B": "Vente à distance sur catalogue spécialisé",
  "47.91Z": "Vente à domicile",
  "47.99Z": "Commerce de détail non effectué en magasin, éventaires ou marchés",
  "49.10Z": "Transport ferroviaire interurbain de voyageurs",
  "49.20Z": "Transports ferroviaires de fret",
  "49.31Z": "Transports urbains de voyageurs",
  "49.32Z": "Transports de voyageurs par taxis",
  "49.39Z": "Autres transports routiers de voyageurs",
  "49.41A": "Transport routier de fret interurbain",
  "49.41B": "Transport routier de fret de proximité (transport urbain de marchandises)",
  "49.42Z": "Transports routiers de fret de lots",
  "49.43Z": "Transports routiers spécialisés de fret",
  "49.49Z": "Autres transports routiers de fret",
  "49.50Z": "Transports par conduites",
  "49.51Z": "Transports aériens interurbains de passagers",
  "49.52Z": "Transports aériens de fret",
  "49.53Z": "Transports de passagers par charter",
  "49.59Z": "Autres transports aériens",
  "49.60Z": "Transports par eau",
  "49.61Z": "Transports maritimes de voyageurs",
  "49.62Z": "Transports maritimes de fret",
  "49.63Z": "Transports fluviaux de voyageurs",
  "49.64Z": "Transports fluviaux de fret",
  "49.69Z": "Transports par eau n.c.a.",
  "49.70Z": "Transports spatiaux",
  "49.81Z": "Transports postaux sous conditions gouvernementales",
  "49.82Z": "Messagerie, fret express",
  "49.83Z": "Autres transports routiers de fret",
  "49.84Z": "Transports multimodaux",
  "49.85Z": "Manutention portuaire",
  "49.90Z": "Autres transports terrestres n.c.a.",
  "50.10Z": "Transport maritime de passagers",
  "50.20Z": "Transport maritime de fret",
  "50.30Z": "Construction navale et services connexes",
  "50.41Z": "Transports fluviaux de passagers",
  "50.42Z": "Transports fluviaux de fret",
  "51.10Z": "Transports aériens de passagers",
  "51.21Z": "Transports de fret aérien",
  "51.22Z": "Transports spatiaux",
  "52.10A": "Entreposage et stockage frigorifiques",
  "52.10B": "Entreposage et stockage non frigorifiques",
  "52.21Z": "Services de transport par camions",
  "52.29Z": "Autres services de transport terrestre",
  "52.30Z": "Transports par conduites (eau, gaz, etc.)",
  "52.4": "Manutention",
  "52.49Z": "Autres services auxiliaires de transport",
  "52.61Z": "Transports de voyageurs par taxis",
  "52.62Z": "Transports de voyageurs par VTC",
  "52.63Z": "Transports urbains",
  "52.64Z": "Transports interurbains",
  "52.70Z": "Services auxiliaires des transports",
  "52.80Z": "Transports par pipeline",
  "53.10Z": "Activités de poste dans le cadre d’une obligation de service universel",
  "53.20Z": "Autres activités de poste et de courrier",
  "55.10Z": "Hébergements touristiques et autres hébergements de courte durée",
  "55.20Z": "Hébergement social pour sans-abri et centres pour migrants",
  "55.90Z": "Autres hébergements",
  "56.10A": "Restauration traditionnelle",
  "56.10B": "Café-brasserie",
  "56.10C": "Restauration de type rapide",
  "56.21Z": "Services de traiteur",
  "56.29A": "Restauration collective sous contrat",
  "56.29B": "Autres services de restauration n.c.a.",
  "56.30Z": "Débits de boissons",
  "58.11Z": "Édition de livres",
  "58.12Z": "Édition de répertoires et fichiers",
  "58.13Z": "Édition de journaux",
  "58.14Z": "Édition de revues et périodiques",
  "58.19Z": "Autres activités d’édition",
  "58.21Z": "Édition de logiciels",
  "58.29C": "Édition de logiciels applicatifs",
  "59.11Z": "Production de films pour le cinéma",
  "59.12Z": "Post-production de films cinématographiques, etc.",
  "59.13Z": "Distribution de films cinématographiques",
  "59.14Z": "Projection de films",
  "59.20Z": "Enregistrement sonore et édition musicale",
  "59.29Z": "Autres activités de production audiovisuelle",
  "60.10Z": "Édition de chaînes généralistes",
  "60.20Z": "Édition de chaînes thématiques",
  "61.10Z": "Télécommunications filaires",
  "61.20Z": "Télécommunications sans fil",
  "61.30Z": "Activité satellite",
  "61.90Z": "Autres activités de télécommunication",
  "62.01Z": "Programmation informatique",
  "62.02A": "Conseil en systèmes et logiciels informatiques",
  "62.02B": "Tierce maintenance de systèmes et d’applications informatiques",
  "62.03Z": "Gestion d’installations informatiques",
  "62.09Z": "Autres activités informatiques",
  "63.11Z": "Traitement de données, hébergement, activités connexes",
  "63.12Z": "Portails Internet",
  "63.91Z": "Gestion de fonds documentaire",
  "63.99Z": "Autres services d’information n.c.a.",
  "64.19Z": "Autres intermédiations monétaires",
  "64.20Z": "Activités de service des finances",
  "64.30Z": "Fiducie",
  "64.91Z": "Crédit-bail",
  "64.99Z": "Services auxiliaires de services financiers",
  "65.11Z": "Assurance vie",
  "65.12Z": "Autres assurances",
  "65.20Z": "Réassurance",
  "66.11Z": "Agences de logement",
  "66.12Z": "Autres activités auxiliaires de services financiers",
  "68.10Z": "Activités des marchands de biens immobliers",
  "68.20A": "Location de logements",
  "68.20B": "Location de terrains",
  "68.31Z": "Agences immobilières",
  "68.32Z": "Administration d’immeubles",
  "68.33Z": "Location de logements non meublés",
  "68.20C": "Location de logements meublés",
  "68.20D": "Location de locaux non résidentiels",
  "68.20E": "Location d’autres biens immobiliers",
  "68.92Z": "Régisseurs d’immeubles",
  "69.10Z": "Activités juridiques",
  "69.20Z": "Activités comptables",
  "70.10Z": "Activités des sièges sociaux",
  "70.21Z": "Conseil en relations publiques et communication",
  "70.22Z": "Conseil pour les affaires et autres conseils de gestion",
  "71.11Z": "Activités d’architecture",
  "71.12A": "Activités d’ingénierie",
  "71.12B": "Contrôle technique, inspection et certification",
  "71.20B": "Analyse, essai et inspection techniques",
  "72.11Z": "Recherche-développement en biotechnologie",
  "72.19Z": "Recherche-développement autres",
  "72.20Z": "Recherche-développement en sciences physiques et naturelles",
  "73.11Z": "Activités des agences de publicité",
  "73.12Z": "Régie publicitaire",
  "73.20Z": "Études de marché et sondages",
  "74.10Z": "Activités spécialisées de design",
  "74.20Z": "Activités photographiques",
  "74.30Z": "Traduction et interprétation",
  "74.90Z": "Autres activités spécialisées",
  "75.00Z": "Activités vétérinaires",
  "77.11B": "Location et location-bail de véhicules de transport de personnes",
  "77.12Z": "Location de camions",
  "77.21Z": "Location de matériel de construction",
  "77.22Z": "Location de matériel de bureau (ordinateurs, etc.)",
  "77.29Z": "Autres locations de machines et équipements",
  "77.39Z": "Location d’autres biens personnels et domestiques",
  "77.40Z": "Leasing et location-bail",
  "78.10Z": "Activités d’emploi",
  "78.20Z": "Mise à disposition de ressources humaines",
  "78.30Z": "Activités intérim",
  "79.11Z": "Activités des agences de voyage",
  "79.12Z": "Activités des voyagistes",
  "79.90Z": "Autres services de réservation",
  "80.10Z": "Activités de sécurité privée",
  "80.20Z": "Activités de services liés à la sécurité",
  "81.10Z": "Activités combinées de soutien lié aux bâtiments",
  "81.21Z": "Entretien courant d’immeubles",
  "81.22Z": "Nettoyage courant des bâtiments",
  "81.29Z": "Autres activités de nettoyage",
  "82.11Z": "Services d’organisation de foires, salons ou congrès",
  "82.19Z": "Activités de conditionnement",
  "82.20Z": "Activités de centres d’appels",
  "82.30Z": "Organisation de jeux de hasard et d’argent",
  "82.99Z": "Autres activités de soutien aux entreprises n.c.a.",
  "84.11Z": "Administration publique générale",
  "84.12Z": "Administration publique (autres) concurrentielle",
  "84.13Z": "Organisation associative",
  "84.24Z": "Commerce extérieur",
  "84.30Z": "Justice",
  "84.32Z": "Sécurité sociale",
  "84.33Z": "Action sociale sans hébergement",
  "84.34Z": "Action sociale avec hébergement",
  "85.11Z": "Enseignement post-primaire",
  "85.12Z": "Enseignement primaire",
  "85.20Z": "Formation continue d’adultes",
  "85.31Z": "Enseignement secondaire",
  "85.32Z": "Autres enseignements",
  "85.41Z": "Enseignement supérieur",
  "85.42Z": "Recherche constituante",
  "86.10Z": "Activités hospitalières",
  "86.21Z": "Activités pour handicapés",
  "86.90Z": "Autres activités de santé humaine",
  "87.10Z": "Hébergement médico-social",
  "87.20Z": "Hébergement social pour personnes âgées",
  "87.30Z": "Hébergement social pour adultes handicapés",
  "88.10Z": "Aide par le travail",
  "88.99Z": "Autre action sociale sans hébergement",
  "90.01Z": "Arts du spectacle vivant",
  "90.02Z": "Support aux spectacles vivants",
  "91.01Z": "Gestion des bibliothèques",
  "91.02Z": "Gestion des archives",
  "91.03Z": "Gestion des musées",
  "91.04Z": "Gestion des sites et monuments historiques",
  "91.05Z": "Gest. des jardins botaniques, zoos et réserves naturelles",
  "92.00Z": "Activités des loteries",
  "93.11Z": "Gestion d’installations sportives",
  "93.12Z": "Activités de clubs de sports",
  "93.13Z": "Activités de fitness",
  "93.19Z": "Autres activités sportives",
  "94.11Z": "Activités d’organisations religieuses",
  "94.12Z": "Activités politiques",
  "94.20Z": "Activités syndicales",
  "94.91Z": "Activités d’organisations associatives",
  "94.92Z": "Activités de coopératives",
  "94.99Z": "Autres activités n.c.a.",
  "95.11Z": "Réparation d’ordinateurs et d’équipements périphériques",
  "95.12Z": "Réparation d’appareils électroniques et optiques",
  "95.21Z": "Réparation d’appareils électroménagers et d’équipements du foyer",
  "95.22Z": "Réparation d’articles personnels et domestiques",
  "96.01A": "Blanchisserie-teinturerie de gros",
  "96.01B": "Blanchisserie, nettoyage à sec de détail",
  "96.02A": "Coiffure",
  "96.02B": "Soins de beauté",
  "96.03Z": "Pompes funèbres",
  "96.04Z": "Entretien corporel",
  "96.09Z": "Autres services personnels n.c.a.",
  "97.00Z": "Activités des ménages en tant qu’employeurs",
  "98.10Z": "Activités indifférenciées des ménages – biens",
  "98.20Z": "Activités indifférenciées des ménages – services",
  "99.00Z": "Activités des organisations et organismes extraterritoriaux",
}

export const organizationTypeByNaf: Record<string, OrganizationType> = {
  "46.42Z": OrganizationType.Brand,
  "46.43Z": OrganizationType.Brand,
  "47.91B": OrganizationType.Distributor,
  "46.49Z": OrganizationType.Brand,
  "14.13Z": OrganizationType.Brand,
  "47.71Z": OrganizationType.Brand,
  "47.64Z": OrganizationType.Brand,
  "82.11Z": OrganizationType.Consultancy,
  "13.96Z": OrganizationType.Brand,
  "46.41Z": OrganizationType.Brand,
  "47.72A": OrganizationType.Brand,
  "70.10Z": OrganizationType.Brand,
  "13.91Z": OrganizationType.Brand,
  "62.02A": OrganizationType.Consultancy,
  "47.91A": OrganizationType.Distributor,
  "14.14Z": OrganizationType.Brand,
  "58.29C": OrganizationType.Consultancy,
  "82.99Z": OrganizationType.Consultancy,
  "15.12Z": OrganizationType.Brand,
  "74.90B": OrganizationType.Consultancy,
  "62.02B": OrganizationType.Consultancy,
  "62.01Z": OrganizationType.Consultancy,
  "14.19Z": OrganizationType.Brand,
  "14.31Z": OrganizationType.Brand,
  "70.22Z": OrganizationType.Consultancy,
}
